### ISSUE TITLE
No funciona con Movistar

### ISSUE THREAD

**Issue by SebaG20xx** [TCattd/Pixel-VoLTE-VoWIFI-5G-Enabler#1]
Probado con un Pixel 6, seguí tu tutorial, pero al reiniciar sigue siendo LTE.
Estoy usando e-sim, por si tiene que ver

**Comment by TCattd** [comment]
Buenas, estimado.

Al momento de probar, cuando cree este módulo, me conseguí chips (con plan o fonos físicos, Pixels, de conocidos que estuvieron dispuestos a perder su tiempo por mi) para poder validar que esto funcionaba.

Actualmente no vivo en "la ciudad". Me tengo que mover a ella para poder probar el 5G de cualquier proveedor.

Estoy constantemente probando el 5G, en un Pixel 8, con los proveedores WOM y Entel.
En ellos, funciona.

¿Algo cambió desde que probé hasta hoy? ¿Fue un error mio? No lo sé.

El uso de eSIM no es el problema. Estoy usando uno con WOM ahora (antes Entel), y no tuve problemas para conectarme a 5G con ese tipo de SIM. El módulo hace su trabajo.

Si se que la red de Movistar, en la ciudad que tengo cerca, es un asco. Es de las peores en cuánto a disponiblidad de 5G. Al menos por acá. Me costó un montón poder dar con una antena 5G, que diera 5G efectivamente, por estos lados.

Ojo que disponibilidad 5G no es lo mismo que antenas capaces de 5G. Ver: https://pisapapeles.net/opensignal-revela-los-operadores-moviles-que-mejor-experiencia-ofrecen-en-chile/

Se también que Movistar en particular se quedó super atrás con el tema del 5G. En las licitaciones, no empujaron más allá que el resto de los proveedores. Ver: https://pisapapeles.net/que-es-el-5g-nsa-5g-sa-y-que-esperamos-del-5g-sobre-banda-milimetrica-en-chile/

Al final, es muy complicado para mi dar soporte a algo como esto (este módulo). Por eso, y preventivamente, el README dice claramente:
This module is provided as is, without any warranty. You are responsible for any damage caused by using this module. Use at your own risk.

Acabo de agregar este texto, que espero deje más claro este punto:
There will be no support given for this module. If you have any issues, please: help fix them yourself, and submit a pull request. Thanks!

Y acomodé el texto inicial de los proveedores, para que diga así:
Only tested on Google Pixel 7 and 8. It might work on other Google devices. Who knows.
Only tested in Chile. Working and actively tested on: Entel & WOM. Should work on Claro & Movistar too.

Lo siento, estimado. De verdad.

Dejé una nueva nota en la guía que mencionas. Por acá:
https://itsaboutactitud.wordpress.com/2024/02/02/habilitando-5g-volte-y-vowifi-en-un-google-pixel-chile/#sin-5g-aun
Quizás eso te funcione.

Si tienes tiempo, ganas y los conocimientos, eres bienvenido a ayudar a "tunear" el módulo y ver que parámetros si te permiten obtener 5G en Movistar en tu ciudad. Cualquier Pull Request con ayuda será agradecido.

Buen dia!

**Comment by SebaG20xx** [comment]
Buenas! Agradezco tu respuesta, lamentablemente no tengo la opción en forcing control de "NR Mode Setting", pero de todas maneras ahora tengo VOLTE, gracias :)

**Comment by SebaG20xx** [comment]
Buenas! Agradezco tu respuesta, lamentablemente no tengo la opción en forcing control de "NR Mode Setting", pero de todas maneras ahora tengo VOLTE, gracias :)

**Comment by TCattd** [comment]
@SebaG20xx recuerda agregarlo al Whitelist en Magisk primero, para que pueda obtener permisos de root. Lo menciono en la guía. Por si acaso faltó aquello.

**Comment by SebaG20xx** [comment]
Si lo hice, pero me daba otras opciones, no la que me dices

**Comment by TCattd** [comment]
¿En serio? :/

https://i.imgur.com/s9xNIij.png

https://i.imgur.com/Cs4mmDU.png

https://i.imgur.com/wA1ifVW.png

https://i.imgur.com/aYGKgz5.png

¿Nada de eso?

**Comment by SebaG20xx** [comment]
El NR Mode setting no lo tengo, solo tengo uno que es de opt
